version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      # Basic Auth
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-securepass123}
      - GENERIC_TIMEZONE=${TIMEZONE:-Asia/Kolkata}
      # Webhook
      - WEBHOOK_URL=${N8N_WEBHOOK_TUNNEL_URL}
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # External Service Config
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Custom
      - CONFIRMATION_KEYWORD=${CONFIRMATION_KEYWORD:-CONFIRM}
      - AUDIT_SHEET_ID=${AUDIT_SHEET_ID}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./workflows:/workflows:ro
      - ./scripts:/scripts:ro
    networks:
      - n8n-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local